[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
hello_anchor = "BqNzK3t72vrMpUZGLPbjUCdSMiz6hWKU1emAQL5Gcrfk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
